prometheus-blackbox-exporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 15s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
      http_backend:
        prober: http
        timeout: 15s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          fail_if_body_not_matches_regexp:
            - "true"
  serviceMonitor:
    enabled: true

    defaults:
      additionalMetricsRelabels: {}
      labels: {}
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
    scheme: http

    tlsConfig: {}
    bearerTokenFile:

    targets:
      - name: dex
        url: https://dex.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: base
        url: https://base.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: faucet
        url: https://faucet.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: aerepl-http
        url: https://repl.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: aesophia
        url: https://compiler.stg.aepps.com/version
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: explorer-mainnet
        url: https://explorer-mainnet.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: explorer-testnet
        url: https://explorer-testnet.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: superhero-ui
        url: https://superhero.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: superhero-wallet
        url: https://superhero-wallet.stg.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: superhero-backend
        url: https://superhero-backend.stg.aepps.com/health/backend
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend

    relabelings:
      # This is the part where, the original SM endpoints passed as parameters to blackbox exporter.
      # More info: https://prometheus.io/docs/guides/multi-target-exporter/#prometheus-config
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
